version: '3.9'

services:

  db:
    image: postgres:15
    container_name: quantdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quantdb
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: quant-api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/quantdb
      ALPHA_VANTAGE_API_KEY: ${ALPHA_VANTAGE_API_KEY}
      ENV: dev
    ports:
      - "8000:8000"